WIP: rebased on sunxi devel
error: could not apply 6f31371... Revert "ALSA: hda - Increment default stream numbers for AMD HDMI controllers"
error: could not apply 579d8f0... x86/efi: Make efi virtual runtime map passing more robust
Could not apply d232ed0... futex: Allow architectures to skip futex_atomic_cmpxchg_inatomic() test
Could not apply 387df1b... Linux 3.14.1

Could not apply 0af8322... exit: call disassociate_ctty() before exit_task_namespaces()
Could not apply 798d3c5... Linux 3.14.2
error: could not apply 45ada9f... x86/efi: Correct EFI boot stub use of code32_start
error: could not apply e504a78... efi: Pass correct file handle to efi_file_{read,close}
Could not apply 1ffddb5... iser-target: Match FRMR descriptors to available session tags
Could not apply af0f657... iser-target: Add missing se_cmd put for WRITE_PENDING in tx_comp_err
Could not apply 549b3cf... ext4: FIBMAP ioctl causes BUG_ON due to handle EXT_MAX_BLOCKS
Could not apply 6292e9c... usb: xhci: Prefer endpoint context dequeue pointer over stopped_trb
Could not apply 185a3af... ARM: tegra: remove UART5/UARTE from tegra124.dtsi
Could not apply 774e1e6... Linux 3.14.3

Change-Id: Id0fa57f594b613826cf48305a60b6d1797afaf6f
Signed-off-by: Philippe Coval <philippe.coval@open.eurogiciel.org>